---
- name: install apache
  yum: name=httpd state=present
- name: create sites directoty
  file: path={{item}} state=directory
  with_items: "{{apache_dirs}}"

- name: copy index.html
  template: src=index.html.j2 dest={{apache_docroot}}/index.html
- name: start apache
  service: name=httpd state=started enabled=yes
